trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: python3 --version
  - script: pip3 install -r requirements.txt
  - script: |
          nohup python3 run.py &
          sleep 1
  - script: python3 tests.py