trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - script: python --version
    - script: pip install -r requirements.txt
    displayName: 'installs required dependencies'
  - job: StartServer
    steps:
      - script: |
          nohup python run.py &
          sleep 1
  - job: TestJob
    steps:
    - script: python tests.py
    displayName: 'Run a multi-line script'